import os

from django.conf import settings


MAX_LENGTH_NAME_RECIPE = 256
MAX_LENGTH_NAME_INGREDIENT = 128
MAX_LENGTH_MEASUREMENT_UNIT = 64
MAX_LENGTH_NAME_TAG = 32
MAX_LENGTH_SLUG_TAG = 32
MAX_LENGTH_NAME = 150
MAX_LENGTH_USERNAME = 150
MAX_LENGTH_LAST_NAME = 150
MAX_LENGTH_FIRST_NAME = 150
MAX_LENGTH_SHORT_CODE = 10
LENGHT_SHORT_CODE = 7
MIN_COOKING_TIME = 1
MIN_AMOUNT = 1
MAX_LENGTH_STR = 50
PATH_INGREDIENTS_CSV = os.path.join(
    settings.BASE_DIR, 'data', 'ingredients.csv')
DEFAULT_TAGS_FILE = settings.BASE_DIR / 'data' / 'tags.csv'
ADMIN_EXTRA = 1
ADMIN_MIN_NUM = 1
LIST_PER_PAGE = 25
PAGE_SIZE = 6
BUFFER_VALUE = 0
MAX_LENGTH_ROW_INGREDIENTS = 2
MAX_LENGTH_ROW_TAGS = 2
