

services:
  db:
    image: postgres:15
    container_name: foodgram-db
    env_file:
      - ../backend/.env
    ports:
      - "5432:5432"  

    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    networks:
      - infra_default

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: foodgram-backend
    env_file:
      - ../backend/.env
    volumes:
      - static:/app/staticfiles
      - media:/app/mediafiles
    depends_on:
      - db
    command: sh entrypoint.sh

    networks:
      - infra_default

  frontend:
    container_name: foodgram-front
    build: ../frontend
    volumes:
      - ../frontend/build:/app/result_build/
    networks:
      - infra_default

  nginx:
    image: nginx:1.25.4-alpine
    container_name: foodgram-proxy
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    volumes:
      - ./nginx.dev.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs:/usr/share/nginx/html/api/docs/
      - static:/usr/share/nginx/html/backend_static/
      - media:/usr/share/nginx/html/media/
    networks:
      - infra_default

volumes:
  pgdata:
  static:
  media:

networks:
  infra_default:
