server {
    listen 80;
    server_name localhost;

    # Отдача фронтенда
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri /index.html;
    }

    # API запросы на Django backend
    location /api/ {
        proxy_pass http://backend:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Django admin
    location /admin/ {
        proxy_pass http://backend:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Файлы из media
    location /media/ {
        alias /usr/share/nginx/html/media/;
        add_header Cache-Control "no-store";
    }

    # Файлы из static (собранные)
    location /backend_static/ {
        alias /usr/share/nginx/html/backend_static/;
        add_header Cache-Control "no-store";
    }

    # Документация
    location /api/docs/ {
        alias /usr/share/nginx/html/api/docs/;
        index redoc.html;
        try_files $uri $uri/ /redoc.html;
    }

}
