# Generated by Django 5.2 on 2025-05-08 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='short_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
