# Generated by Django 5.2 on 2025-05-08 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_short_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-05-08 18:30:00'),
            preserve_default=False,
        ),
    ]
