# Generated by Django 5.2 on 2025-05-24 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_subscriptions_author_alter_subscriptions_user_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscriptions',
            new_name='Subscription',
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ['user__username'], 'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписки'},
        ),
    ]
